Create database customer_behavior;
select * from customer_behavior.customer;
select * from customer_behavior.customer limit 20
USE customer_behavior;

--Q1. What is the total revenue generated by male vs. female customers?
SELECT
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase
amount?
SELECT
    customer_id,
    item_purchased,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >
(
    SELECT AVG(purchase_amount)
    FROM customer
);

--Q3. Which are the top 5 products with the highest average review rating?
SELECT
    item_purchased,
    ROUND(AVG(review_rating),2) AS average_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount),2) AS average_purchase
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between
subscribers and non-subscribers.
SELECT
    subscription_status,
    ROUND(AVG(purchase_amount),2) AS average_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    item_purchased,

ROUND(
(
SUM(
CASE
WHEN discount_applied='Yes'
THEN 1
ELSE 0
END
)
/ COUNT(*)
)*100
,2) AS discount_percentage

FROM customer

GROUP BY item_purchased

ORDER BY discount_percentage DESC

LIMIT 5;
--Q7. Segment customers into New, Returning, and Loyal based on their total number of
previous purchases, and show the count of each segment.
SELECT

CASE

WHEN previous_purchases <= 1
THEN 'New'

WHEN previous_purchases BETWEEN 2 AND 5
THEN 'Returning'

ELSE 'Loyal'

END AS customer_segment,

COUNT(*) AS total_customers

FROM customer

GROUP BY customer_segment;
--Q8. What are the top 3 most purchased products within each category?
WITH ranked_products AS
(
SELECT

category,
item_purchased,

COUNT(*) AS purchase_count,

ROW_NUMBER() OVER
(
PARTITION BY category
ORDER BY COUNT(*) DESC
) AS ranking

FROM customer

GROUP BY category,item_purchased
)

SELECT *

FROM ranked_products

WHERE ranking <= 3;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to
subscribe?
SELECT

subscription_status,

COUNT(*) AS customer_count,

ROUND(
COUNT(*)*100/
(
SELECT COUNT(*)
FROM customer
WHERE previous_purchases > 5
),
2
) AS percentage

FROM customer

WHERE previous_purchases > 5

GROUP BY subscription_status;
--Q10. What is the revenue contribution of each age group?
SELECT

age_group,

SUM(purchase_amount) AS revenue,

ROUND(
SUM(purchase_amount)*100/
(
SELECT SUM(purchase_amount)
FROM customer
),
2
) AS contribution_percentage

FROM customer

GROUP BY age_group

ORDER BY revenue DESC;